services:
    mongodb:
        image: mongodb/mongodb-community-server:latest
        container_name: mongodb
        restart: unless-stopped
        ports:
            - "27017"
        volumes:
            - mongodb:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: hanich
            MONGO_INITDB_ROOT_PASSWORD: Qaz12345
 
volumes:
    mongodb:
        external: true